//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersimosMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cliente
    {
        public long IdCliente { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<bool> Sexo { get; set; }
        public string Email { get; set; }
        public Nullable<int> IdDirrecion { get; set; }

        [Display(Name = "Provincia")]
        public Nullable<int> IdProvincia { get; set; }
        [Display(Name = "Distrito")]
        public Nullable<int> IdDistrito { get; set; }
        [Display(Name = "Corregimiento")]
        public Nullable<int> IdCorregimiento { get; set; }
    
        public virtual CatCorregimientos CatCorregimientos { get; set; }
        public virtual CatDistritos CatDistritos { get; set; }
        public virtual CatProvincia CatProvincia { get; set; }
    }
}
